# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='savePath',
            field=models.FileField(upload_to='JAE/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='savePath',
            field=models.FileField(upload_to='TEMP/'),
        ),
    ]
